# Generated by Django 6.0.1 on 2026-01-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='service_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='service_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
