# Generated by Django 6.0.1 on 2026-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_system', '0002_queue_service_end_time_queue_service_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='priority_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queue',
            name='skip_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
