# Generated by Django 6.0.1 on 2026-01-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('hospital', 'Hospital'), ('ration_shop', 'Ration Shop'), ('bank', 'Bank'), ('government_office', 'Government Office')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('num_counters', models.IntegerField(default=1)),
                ('avg_service_time', models.IntegerField(default=5)),
            ],
        ),
    ]
