# Generated by Django 6.0.1 on 2026-01-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_token_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='paused',
            field=models.BooleanField(default=False),
        ),
    ]
