# Generated by Django 6.0.1 on 2026-01-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_number_remove_user_sms_opt_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sms_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
