# Generated by Django 6.0.1 on 2026-01-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('token_created', 'Token Created'), ('token_next', 'Token Next'), ('token_serving', 'Token Serving'), ('token_skipped', 'Token Skipped'), ('token_cancelled', 'Token Cancelled'), ('token_completed', 'Token Completed')], max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('provider_id', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('queue_id', 'event_type')},
            },
        ),
    ]
